Models/ConfigurationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nop.Web.Framework.Models;
using Nop.Web.Framework.Mvc.ModelBinding;

namespace Nop.Plugin.Misc.BillingoInvoicing.Models
{
    public record ConfigurationModel : BaseNopModel
    {
        [NopResourceDisplayName("Plugins.Misc.BillingoInvoicing.Fields.ApiKey")]
        public string ApiKey { get; set; }
        [NopResourceDisplayName("Plugins.Misc.BillingoInvoicing.Fields.BlockId")]
        public int BlockId { get; set; }
    }
}

Controllers/BillingoInvoicingController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Misc.BillingoInvoicing.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Misc.BillingoInvoicing.Controllers
{
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    [AuthorizeAdmin]
    public class BillingoInvoicingController : BasePluginController
    {
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;
        private readonly INotificationService _notificationService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;

        public BillingoInvoicingController(
            ISettingService settingService, 
            IStoreContext storeContext,
            INotificationService notificationService,
            ILocalizationService localizationService,
            IPermissionService permissionService)
        {
            _settingService = settingService;
            _storeContext = storeContext;
            _notificationService = notificationService;
            _localizationService = localizationService;
            _permissionService = permissionService;
        }

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<BillingoInvoicingSettings>(storeId);

            var model = new ConfigurationModel()
            {
                ApiKey = settings.ApiKey,
                BlockId = settings.BlockId
            };

            return View("~/Plugins/Misc.BillingoInvoicing/Views/Configure.cshtml", model);
        }

        [HttpPost, ActionName("Configure")]
        [FormValueRequired("save")]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageWidgets))
                return AccessDeniedView();

            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var settings = await _settingService.LoadSettingAsync<BillingoInvoicingSettings>(storeId);

            //set new settings values
            settings.ApiKey = model.ApiKey;
            settings.BlockId = model.BlockId;

            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.ApiKey, true, storeId, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(settings, setting => setting.BlockId, true, storeId, false);

            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }
    }
}

Views/Configure.cshtml
@model ConfigurationModel

@{
	Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync(typeof(StoreScopeConfigurationViewComponent))

<form asp-controller="BillingoInvoicing" asp-action="Configure" method="post">
	<div class="cards-group">
		<div class="card card-default card-outline card-info" id="pnlOnboarding">
			<div class="card-header">
				@T("Plugins.Misc.BillingoInvoicing.Title")
			</div>
			<div class="card-body">
				<p>
					Ez egy NopCommerce automatikus számlageneráló plugin a <a href="https://www.billingo.hu/ target=" _blank"">Billingo számlázórendszerhez</a>.<br />
					Szükséges, hogy legyen <a href="https://www.billingo.hu/arak/api-tomeges" target="_blank">API és tömeges számlagenerálás előfizetése</a>.<br />
					Kizárólag saját felelősségre használható!<br />
					Hozzon létre egy V3 API kulcsot: <a href="https://support.billingo.hu/content/2092531786" target="_blank">Hol tudok API kulcsot generálni?</a>
					Hozzon létre egy számlatömböt: <a href="https://support.billingo.hu/content/918716465">Új bizonylattömb létrehozása</a>
				</p>
				<hr />
				<div class="form-group row">
					<div class="col-md-3">
					<nop-label asp-for="ApiKey" />
					</div>
					<div class="col-md-9">
						<nop-editor asp-for="ApiKey" asp-required="true" />
						<span asp-validation-for="ApiKey"></span>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-md-3">
						<nop-label asp-for="BlockId" />
					</div>
					<div class="col-md-9">
						<nop-editor asp-for="BlockId" asp-required="true" />
						<span asp-validation-for="BlockId"></span>
					</div>
				</div>
				<div class="form-group row" id="pnlSave">
					<div class="col-md-9 offset-md-3">
						<button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>